### ISSUE TITLE
[AlignPoints.py] eats BCPs

### ISSUE THREAD

**Issue by frankrolf** [ryanbugden/Robofont#2]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/2049645/54149941-a2661580-4437-11e9-9e69-f16bcd07f419.png">

**Comment by ryanbugden** [comment]
Hey, thanks Frank. Was this after running the script once with the top two points selected?

**Comment by ryanbugden** [comment]
Can't reproduce this issue on a curve this size anymore. In there I have a `ocp_dist_threshold` setting. You can change this depending on the point distance within which you want it to eat the BCPs (may be helpful for some situations, not sure yet). Can also set it to `0`.

**Comment by frankrolf** [comment]
Fixed in fa9df7f33ec404ddb4304cd2bb436ee3ff5f008b.
Still seeing some debug print statements here: https://github.com/ryanbugden/Robofont/blob/master/_scripts/AlignPoints.py#L109
